txt = input("zadej text: ")
typ = input("vyber šifru:\n============\n[M]orseovka\n[B]raillovo písmo\n")

if typ == "m" or typ == "M":
    print("morse")
if typ == "b" or typ == "B":
    print("braille")
else:
    print("chyba!")

a = dict(morse = ".-", braille = "")
b = dict(morse = "-...", braille = "")
c = dict(morse = "", braille = "")
d = dict(morse = "", braille = "")
e = dict(morse = "", braille = "")
f = dict(morse = "", braille = "")
g = dict(morse = "", braille = "")
h = dict(morse = "", braille = "")
i = dict(morse = "", braille = "")
j = dict(morse = "", braille = "")
k = dict(morse = "", braille = "")
l = dict(morse = "", braille = "")
m = dict(morse = "", braille = "")
n = dict(morse = "", braille = "")
o = dict(morse = "", braille = "")
p = dict(morse = "", braille = "")
q = dict(morse = "", braille = "")
r = dict(morse = "", braille = "")
s = dict(morse = "", braille = "")
t = dict(morse = "", braille = "")
u = dict(morse = "", braille = "")
v = dict(morse = "", braille = "")
w = dict(morse = "", braille = "")
x = dict(morse = "", braille = "")
y = dict(morse = "", braille = "")
z = dict(morse = "", braille = "")
